package cop4331.financemanager.controller;

import cop4331.financemanager.model.FinanceModel;
import cop4331.financemanager.model.Transaction;
import cop4331.financemanager.model.TransactionType;
import cop4331.financemanager.view.MainFrame;
import cop4331.financemanager.view.TransactionFormDialog;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Controller for the "Add Expense" use case (UC2).
 * <p>
 * Responsibilities:
 * <ul>
 *     <li>Open the {@link TransactionFormDialog} in EXPENSE mode.</li>
 *     <li>Validate that the new expense does not exceed the current balance.</li>
 *     <li>Add the expense transaction to the {@link FinanceModel} if valid.</li>
 * </ul>
 *
 */
public class AddExpenseController implements ActionListener, TransactionFormDialog.Listener {

    private final FinanceModel model;
    private final MainFrame mainFrame;
    private final TransactionFormDialog formDialog;

    /**
     * Creates a controller for handling the Add Expense use case.
     *
     * @param model      the finance model; must not be {@code null}
     * @param mainFrame  the main application frame; must not be {@code null}
     * @param formDialog the dialog used to enter expense data; must not be {@code null}
     */
    public AddExpenseController(FinanceModel model,
                                MainFrame mainFrame,
                                TransactionFormDialog formDialog) {
        this.model = model;
        this.mainFrame = mainFrame;
        this.formDialog = formDialog;
    }

    /**
     * Invoked when the "Add Expense" button is pressed.
     * Opens the {@link TransactionFormDialog} in EXPENSE mode.
     *
     * @param e the action event generated by the button
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        formDialog.setListener(this);
        formDialog.openForAdd(TransactionType.EXPENSE);
    }

    /**
     * Called by the dialog when the user clicks Save.
     * Validates that the expense does not exceed the current balance
     * and either shows a validation error or adds the transaction.
     *
     * @param tx the expense transaction submitted by the user
     */
    @Override
    public void saveClicked(Transaction tx) {
        double futureBalance = model.getCurrentBalance() - tx.getAmount();
        if (futureBalance < 0) {
            formDialog.showValidationError("Expense exceeds balance");
            return;
        }
        model.addTransaction(tx);
    }

    /**
     * Called by the dialog when the user cancels.
     * No changes are applied to the model.
     */
    @Override
    public void canceled() {
        // no-op: user canceled the operation
    }
}
