package cop4331.financemanager.controller;



import cop4331.financemanager.model.FinanceModel;
import cop4331.financemanager.model.Transaction;
import cop4331.financemanager.model.TransactionType;
import cop4331.financemanager.view.MainFrame;
import cop4331.financemanager.view.TransactionFormDialog;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Controller for the "Add Income" use case (UC1).
 * <p>
 * Responsibilities:
 * <ul>
 *     <li>Open the {@link TransactionFormDialog} in INCOME mode.</li>
 *     <li>Receive the created {@link Transaction} from the dialog.</li>
 *     <li>Add the new transaction to the {@link FinanceModel}.</li>
 * </ul>
 */
public class AddIncomeController implements ActionListener, TransactionFormDialog.Listener {

    private final FinanceModel model;
    private final MainFrame mainFrame;
    private final TransactionFormDialog formDialog;

    /**
     * Creates a controller for handling the Add Income use case.
     *
     * @param model      the finance model; must not be {@code null}
     * @param mainFrame  the main application frame; must not be {@code null}
     * @param formDialog the dialog used to enter income data; must not be {@code null}
     */
    public AddIncomeController(FinanceModel model,
                               MainFrame mainFrame,
                               TransactionFormDialog formDialog) {
        this.model = model;
        this.mainFrame = mainFrame;
        this.formDialog = formDialog;
    }

    /**
     * Invoked when the "Add Income" button is pressed.
     * Opens the {@link TransactionFormDialog} in INCOME mode.
     *
     * @param e the action event generated by the button
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        formDialog.setListener(this);
        formDialog.openForAdd(TransactionType.INCOME);
    }

    /**
     * Called by the dialog when the user clicks Save.
     * Adds the new income transaction to the model.
     *
     * @param tx the income transaction submitted by the user
     */
    @Override
    public void saveClicked(Transaction tx) {
        model.addTransaction(tx);
        // MainFrame will refresh via ChangeListener
    }

    /**
     * Called by the dialog when the user cancels.
     * No changes are applied to the model.
     */
    @Override
    public void canceled() {
        // nothing special for now
    }
}
