package cop4331.financemanager.controller;



import cop4331.financemanager.model.FinanceModel;
import cop4331.financemanager.view.MainFrame;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Controller for UC5: Delete Transaction.
 * <p>
 * Responsibilities:
 * <ul>
 *     <li>Read the currently selected transaction from the table.</li>
 *     <li>Ask the user for confirmation before deleting.</li>
 *     <li>Request deletion from the {@link FinanceModel}.</li>
 * </ul>
 */
public class DeleteTransactionController implements ActionListener {

    private final FinanceModel model;
    private final MainFrame mainFrame;

    /**
     * Creates a controller for handling the Delete Transaction use case.
     *
     * @param model     the finance model; must not be {@code null}
     * @param mainFrame the main application frame; must not be {@code null}
     */
    public DeleteTransactionController(FinanceModel model, MainFrame mainFrame) {
        this.model = model;
        this.mainFrame = mainFrame;
    }

    /**
     * Invoked when the Delete button is pressed.
     * Prompts the user to confirm and, if confirmed, deletes the selected transaction.
     *
     * @param e the action event generated by the Delete button
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        int id = mainFrame.getTablePanel().getSelectedTransactionId();
        if (id < 0) {
            JOptionPane.showMessageDialog(mainFrame, "Please select a transaction to delete.");
            return;
        }
        int result = JOptionPane.showConfirmDialog(
                mainFrame,
                "Delete selected transaction?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );
        if (result == JOptionPane.YES_OPTION) {
            model.deleteTransaction(id);
        }
    }
}
