package cop4331.financemanager.controller;

import cop4331.financemanager.model.FinanceModel;
import cop4331.financemanager.model.Transaction;
import cop4331.financemanager.view.MainFrame;
import cop4331.financemanager.view.TransactionFormDialog;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Controller for UC4: Edit Transaction (with cancel).
 * <p>
 * Responsibilities:
 * <ul>
 *     <li>Open the {@link TransactionFormDialog} pre-populated with the selected transaction.</li>
 *     <li>Track which transaction is currently being edited.</li>
 *     <li>Apply changes to the {@link FinanceModel} when the user saves.</li>
 * </ul>
 */
public class EditTransactionController implements ActionListener, TransactionFormDialog.Listener {

    private final FinanceModel model;
    private final MainFrame mainFrame;
    private final TransactionFormDialog formDialog;
    private int currentId = -1;

    /**
     * Creates a controller for handling the Edit Transaction use case.
     *
     * @param model      the finance model; must not be {@code null}
     * @param mainFrame  the main application frame; must not be {@code null}
     * @param formDialog the dialog used to edit a transaction; must not be {@code null}
     */
    public EditTransactionController(FinanceModel model,
                                     MainFrame mainFrame,
                                     TransactionFormDialog formDialog) {
        this.model = model;
        this.mainFrame = mainFrame;
        this.formDialog = formDialog;
    }

    /**
     * Invoked when the Edit button is pressed.
     * Loads the selected transaction, opens the dialog in edit mode,
     * and wires this controller as the dialog listener.
     *
     * @param e the action event generated by the Edit button
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        int id = mainFrame.getTablePanel().getSelectedTransactionId();
        if (id < 0) {
            JOptionPane.showMessageDialog(mainFrame, "Please select a transaction to edit.");
            return;
        }
        Transaction tx = model.getTransactionById(id);
        if (tx == null) {
            JOptionPane.showMessageDialog(mainFrame, "Transaction not found.");
            return;
        }
        currentId = id;
        formDialog.setListener(this);
        formDialog.openForEdit(tx);
    }

    /**
     * Called by the {@link TransactionFormDialog} when the user clicks Save.
     * Applies the new transaction data to the model using the stored {@code currentId}.
     *
     * @param newData the updated transaction data; must not be {@code null}
     */
    @Override
    public void saveClicked(Transaction newData) {
        model.editTransaction(currentId, newData);
    }

    /**
     * Called by the {@link TransactionFormDialog} when the user cancels.
     * No changes are applied to the model.
     */
    @Override
    public void canceled() {
        // nothing
    }
}
