package cop4331.financemanager.controller;



import cop4331.financemanager.model.FinanceModel;
import cop4331.financemanager.model.SummaryDTO;
import cop4331.financemanager.view.MainFrame;
import cop4331.financemanager.view.SummaryDialog;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.YearMonth;

/**
 * Controller for UC3: View Summary.
 * <p>
 * Responsibilities:
 * <ul>
 *     <li>Prompt the user for the target year and month.</li>
 *     <li>Request a {@link SummaryDTO} from the {@link FinanceModel}.</li>
 *     <li>Display the summary using the {@link SummaryDialog}.</li>
 * </ul>
 */
public class ViewSummaryController implements ActionListener {

    private final FinanceModel model;
    private final MainFrame mainFrame;
    private final SummaryDialog summaryDialog;

    /**
     * Creates a controller for handling the View Summary use case.
     *
     * @param model         the finance model; must not be {@code null}
     * @param mainFrame     the main application frame; must not be {@code null}
     * @param summaryDialog the dialog used to display monthly summaries; must not be {@code null}
     */
    public ViewSummaryController(FinanceModel model,
                                 MainFrame mainFrame,
                                 SummaryDialog summaryDialog) {
        this.model = model;
        this.mainFrame = mainFrame;
        this.summaryDialog = summaryDialog;
    }

    /**
     * Invoked when the "View Summary" button is pressed.
     * Asks the user for year and month, retrieves the monthly summary from the model,
     * and displays it in the {@link SummaryDialog}.
     *
     * @param e the action event generated by the button
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        String yearStr = JOptionPane.showInputDialog(mainFrame, "Year (e.g. 2025):");
        String monthStr = JOptionPane.showInputDialog(mainFrame, "Month (1-12):");
        if (yearStr == null || monthStr == null) {
            return;
        }
        try {
            int year = Integer.parseInt(yearStr.trim());
            int month = Integer.parseInt(monthStr.trim());
            YearMonth ym = YearMonth.of(year, month);
            SummaryDTO dto = model.getMonthlySummary(ym);
            summaryDialog.showSummary(dto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(mainFrame, "Invalid year/month.");
        }
    }
}
